version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra_node
    ports:
      - "9042:9042"  # CQL native transport port
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./cassandra-init.sh:/docker-entrypoint-initdb.d/cassandra-init.sh
    environment:
      - CASSANDRA_CLUSTER_NAME=JobSchedulerCluster
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
      - CASSANDRA_DC=datacenter1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_AUTHENTICATOR=cassandra
      - CASSANDRA_SUPERUSER_USERNAME=admin
      - CASSANDRA_SUPERUSER_PASSWORD=admin
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  cassandra_data:
    driver: local

networks:
  cassandra_network:
    driver: bridge